# Generated by Django 4.0.6 on 2022-07-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='userdata',
            name='date_added',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
